# Generated by Django 4.2.1 on 2023-07-07 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cliente',
            fields=[
                ('runCliente', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreCliente', models.CharField(max_length=30)),
                ('apPaternoCliente', models.CharField(max_length=30)),
                ('apMaternoCliente', models.CharField(max_length=30)),
                ('direccionCliente', models.CharField(max_length=30)),
                ('telefonoCliente', models.IntegerField()),
                ('correoCliente', models.EmailField(max_length=30)),
                ('contraseñaCliente', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='estado_despacho',
            fields=[
                ('idEstado', models.AutoField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='producto',
            fields=[
                ('idProducto', models.AutoField(primary_key=True, serialize=False)),
                ('nombreProducto', models.CharField(max_length=20)),
                ('precioProducto', models.IntegerField()),
                ('stockProducto', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='promocion',
            fields=[
                ('idPromocion', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPromocion', models.DateField()),
                ('descuentoPromocion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='region',
            fields=[
                ('idRegion', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='suscripcion',
            fields=[
                ('runSuscriptor', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('montoSuscripcion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='tipoUsuario',
            fields=[
                ('idTipoUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTipoUsuario', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='provincia',
            fields=[
                ('idProvincia', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_provincia', models.CharField(max_length=50)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.region')),
            ],
        ),
        migrations.CreateModel(
            name='pedido',
            fields=[
                ('idPedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechaPedido', models.DateField()),
                ('descuentoPedido', models.IntegerField()),
                ('totalPedido', models.IntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='empleado',
            fields=[
                ('runEmpleado', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreEmpleado', models.CharField(max_length=30)),
                ('apPaternoEmpleado', models.CharField(max_length=30)),
                ('apMaternoEmpleado', models.CharField(max_length=30)),
                ('contraseñaEmpleado', models.CharField(max_length=30)),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.tipousuario')),
            ],
        ),
        migrations.CreateModel(
            name='detallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidadProducto', models.IntegerField()),
                ('subtotalPedido', models.IntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='despacho',
            fields=[
                ('idDespacho', models.AutoField(primary_key=True, serialize=False)),
                ('fechaDespacho', models.DateField()),
                ('fechaEntrega', models.DateField()),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.estado_despacho')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='comuna',
            fields=[
                ('idComuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=30)),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.provincia')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='comuna',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.comuna'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipoUsuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Webapp.tipousuario'),
        ),
    ]
